# Generated by Django 4.2.1 on 2023-06-17 12:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="product_type",
        ),
    ]
