# Generated by Django 4.2.1 on 2023-06-17 11:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_alter_category_name_alter_category_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="brand",
        ),
        migrations.DeleteModel(
            name="Brand",
        ),
    ]
